### PR TITLE
Update to Fedora 37

### PR DESCRIPTION
**Pull request by frenzymadness**
Fedora 36 EOL is in the middle of May so I't time to start testing the update.

### CODE REVIEW

**Comment by hroncok** [comment]
The README also mentions PyPy 3.7.

**Comment by frenzymadness** [comment]
> The README also mentions PyPy 3.7.

Fixed, thanks!

**Review by hroncok — APPROVED** [review]
Looks good, but please wait for the week of the actual EOL before shipping it.

**Comment by frenzymadness** [comment]
> Looks good, but please wait for the week of the actual EOL before shipping it.

Why? Do you think F36 will receive any important updates that late?

**Comment by hroncok** [comment]
> Why?

Because that is our documented strategy here.

> Do you think F36 will receive any important updates that late?

Nope.

**Comment by frenzymadness** [comment]
Well, the switch to F37 does not remove F36 from the registry and I wanted to have some time to prepare the github action but I guess it can wait. Hope I wont't forget about it.

**Comment by hroncok** [comment]
Let's do it today.

**Pull request merged**
