### PR TITLE
Python 3.9

### PR DESCRIPTION
**Pull request by hroncok**
I've used the GitHub web editor for this, you might want to squash when merging.

### CODE REVIEW

**Comment by hroncok** [comment]
```
py39 create: /src/.tox/py39
py39 installdeps: pytest
py39 installed: attrs==19.3.0,importlib-metadata==1.5.0,more-itertools==8.2.0,packaging==20.1,pluggy==0.13.1,py==1.8.1,pyparsing==2.4.6,pytest==5.3.5,six==1.14.0,wcwidth==0.1.8,zipp==2.1.0
py39 run-test-pre: PYTHONHASHSEED='139921660'
py39 run-test: commands[0] | pytest
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
cachedir: .tox/py39/.pytest_cache
rootdir: /src
collected 10 items                                                             
test_fac.py ..........                                                   [100%]
============================== 10 passed in 0.03s ==============================
___________________________________ summary ____________________________________
  py39: commands succeeded
  congratulations :)
```

Not nice.

**Comment by hroncok** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1798929

**Comment by frenzymadness** [comment]
Waiting for https://bodhi.fedoraproject.org/updates/FEDORA-2020-5a7bc7cd39

**Comment by frenzymadness** [comment]
Squashed and merged manually. Thank you!

**Pull request closed without merging**
