### PR TITLE
Build the Docker image for multiple architectures

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by hroncok** [comment]
Now I just hope that Docker lets us upload the image from multiple architectures without issues, but I have no way of trying.

**Comment by hroncok** [comment]
The aarch64 (arm64) job takes wuite some time to finish. If we want to, we could skip the dnf_install test there to save quite some time.

**Comment by frenzymadness** [comment]
This looks very good, thank you. I'm going to merge this and check whether Docker hub is able to provide multiple images with different architectures under one name:tag combo out of the box or not. If not, this can be done via a manifest I eventually prepare.

**Comment by frenzymadness** [comment]
I have to find a way to create a manifest manually in Travis :disappointed:

**Pull request merged**
