### PR TITLE
Switch the base image to Fedora 34

### PR DESCRIPTION
**Pull request by frenzymadness**
SSIA and it works well on my machine. Do we have some tests for the Github Action using this image?

### CODE REVIEW

**Comment by hroncok** [comment]
> Do we have some tests for the Github Action using this image?

What do you mean?

> Release pygit2 version limit 

Let's pin to the Fedora 34 version instead?

**Comment by frenzymadness** [comment]
> What do you mean?

Is there any way to test the Github action based on this image before we update it?

> Let's pin to the Fedora 34 version instead?

I had a paragraph written about why I'd like to keep it open but we just need to test the compilation and we probably won't do an incompatible update in Fedora 34 so locking it is not a bad idea. Will do it.

**Comment by hroncok** [comment]
If the updated image is uploaded to dockerhub under some hash id or similar, we might be able to open a draft PR for the tox action to test it.

**Comment by frenzymadness** [comment]
I see. It's not pushed automatically but I can do it manually. But I see that there is only one very simple test in the repo itself so it's not worth it.

I'd merge this PR and then open a new one in one of my projects to test the action on something more complex.

**Comment by hroncok** [comment]
> I'd merge this PR...

Let's do that?

**Pull request merged**
